spring:
  datasource:
    url: jdbc:mysql://10.147.20.134:3306/hpe?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
  redis:
    host: 10.147.20.134
    port: 6379
    password:
  profiles:
    active:
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.liuxinchi.mumu_mall.model.pojo

file:
  upload:
    dir: /home/liuxinchi/hpe/upload/
    ip: 127.0.0.1

ssh:
  hostname: 10.147.20.134
  port: 22
  user: liuxinchi
  password: 592295lxc

command:
  estimate:
    image:
      prefix: /home/liuxinchi/data/openpose-1.7.0/build/examples/openpose/openpose.bin --image_dir
      suffix: --write_json /home/liuxinchi/hpe/output/json --write_images /home/liuxinchi/hpe/output/skeletonimage --model_pose MPI --display 0
    video:
      prefix: /home/liuxinchi/data/openpose-1.7.0/build/examples/openpose/openpose.bin --video
      suffix: --model_pose MPI --display 0 --write_video /home/liuxinchi/hpe/output/video/
  reconstruct:
    image:
      prefix: cd data/hmr/;/home/liuxinchi/.conda/envs/hmr/bin/python -m demo
      imgpath: --img_path /home/liuxinchi/hpe/upload/
      outputimgpath: --output_img_path /home/liuxinchi/hpe/output/meshimage/
      outputmeshpath: --output_mesh_path /home/liuxinchi/hpe/output/mesh/
      jsonpath: --json_path /home/liuxinchi/hpe/output/json/
